### ISSUE TITLE
Stats/Magic Items/ Pts in WM Revolution differ

### ISSUE THREAD

**Issue by LargoW** [dsusco/wm-selector#20]
The points and stats are still based on the last release of WMR.

Please bring these up to version 1.22
http://aldikova.galerka.org/Warmaster/WMR%20armies1.22.pdf

Please note that the magic items also got a huge change by Introducing points depending on Hits/Armour
http://aldikova.galerka.org/Warmaster/WMR1.2.changes.pdf

The changes document listed on the website also has an overview on the changes so you dont have to fork the PDF. It does not list the changes in the main book though
https://wm-revolution.com/file/4/warmaster-revolution-updates-for-2022-final-draft.pdf

**Comment by Elenfir** [comment]
@LargoW Hi I made a Pull request for this and it's awaiting approval

**Comment by LargoW** [comment]
Nice. But it does not include tge 2021 changes, Ogee Kingdom Yhetis for example changed in ruling and points

**Comment by Elenfir** [comment]
I'll try and make time to add those as well

**Comment by Elenfir** [comment]
@LargoW Updated the core rules and the "developmental". Also added the magic weapons that were earlier in the developmental to the core. You can fetch the magic-items branch, since it's a collection of all changes, to run it locally or we can wait and see if it gets approved by @dsusco 

Cheers!

**Comment by leberechtreinhold** [comment]
Is there any news regarding this? I setup locally @Elenfir's PR and it looks good, but since everyone is used to the url of this repo, this is causing confusion. Also I'm not sure if I can go straight to host another version, since this project doesn't have a license and thus, technically all work is copyrighted by default.

**Comment by Elenfir** [comment]
@leberechtreinhold We're also hosting this for use in the warmaster sweden community. I did get approval for hosting it, temporarily at least. But imho I think it's better if this site would be up to date with the latest rules. A lot easier for the community as a whole. @dsusco said he would be able to review at mid august. But haven't heard anything after that.

**Comment by dsusco** [comment]
I just pushed the magic item price changes.
