### ISSUE TITLE
Stats Error Wood Elves WMR

### ISSUE THREAD

**Issue by TheTrueEvilGod** [dsusco/wm-selector#28]
The Branchwraith is listed as a Wizard although it is listed as a Hero in WMR_armies2.23.1

I hope this is the right replace to report this.

Keep up the good work!

**Comment by dsusco** [comment]
Yup. Fix is in, it should be deployed in a few minutes.

**Comment by TheTrueEvilGod** [comment]
Thanks for the quick fix!
