### ISSUE TITLE
Please add unit Min/Max to Touch Selector

### ISSUE THREAD

**Issue by TheTrueEvilGod** [dsusco/wm-selector#29]
Your army tool is great and the touch selector (or mobile selector tab) is working great. I even find myself using it while i am at my pc, because i feel it is quicker to add and remove units with the Plus and Minus signs.

But it is missing  key information: what are the min/max per 1000pts of each unit. The "classic" selector tab has this info.

**Comment by dsusco** [comment]
I'm leery of adding too much info to that page, so I added a popover with the info. Just click or hover on the unit name in the mobile selector and you should see it. The change should be live in a few minutes.

**Comment by TheTrueEvilGod** [comment]
Works. Thanks a lot
