### ISSUE TITLE
Max unit size calculations not running for 2000+ (3000) points armies

### ISSUE THREAD

**Issue by jlmelladovalle** [dsusco/wm-selector#34]
If you add units to a 1999 points limits, min./max. units calculations are OK; the problem comes when you override 2000 points: app maintains 2000 army points calculations.
This can be solved using:
min. * rounded (points/1000)
and (obviously)
max. * rounded (points / 1000)
![Captura de pantalla 2023-11-06 a las 9 10 12](https://github.com/dsusco/wm-selector/assets/10785829/cd62e98b-c9c1-4253-bfa8-a2d7c1241d92)

**Comment by elemorelli** [comment]
Maybe add an input to set the desired army size and perform the validations from that value?

**Comment by dsusco** [comment]
Once you hit 3,000 points the app will evaluate the list as a 3,000 point army, 2,000-2,999 points use the 2k min and max values and is the reason you're seeing the errors in your screenshot. Add +15 points of swords to the list above and you'll be good. Rounding would break point levels at non-1000 increments (1,500 for example uses 1k limits, not 2k).

@elemorelli I've thought about that before, there just hasn't been much demand for it. If that changes I'll see about adding it down the road.

**Comment by jlmelladovalle** [comment]
That's the problem. If you want to play a 1000 pts game, limits must evaluate between 0 to 1000. For 2000, between 1001 to 2000.
Some players, including me (obviously), played massive battles at 3000 points as described in Revolution ruleset.
I had cloned the proyect to have an idea of how you calculate point sections, or if you specify them into cases clauses.
I'll try to resolve it in a mathematic manner and send a merge request. Must I work in a new branch?

And, if you are interested in a Spanish translation to add, I can push a new brach for that.

**Comment by jlmelladovalle** [comment]
Hi. I pushed almost a year ago a merge request solving this issue, but was not attended. Is the project continued?

**Comment by dsusco** [comment]
The change is breaking. 1500 point army lists use 1k minimum and maximums, not 2k that this change would enforce. The app is evaluating at the 2k mins/maxes in your screenshot above because your total isn't yet 3k. Add 15 points of magic items and it'll work.

The Armies book spells this out:

    You may have decided your armies will be chosen to 1500
    points or some other odd number. In this case determine
    min/max values by rounding your actual army size down
    to the next full 1000‘s. So, a 1500 point army is selected
    using the minimums and maximums for a 1000 point
    army, a 2250 point army is the same as a 2000 and so on.

Another way to approach this would be to specify the maximum number of points the army can be, and use that to evaluate the mins/maxes. But using magic items to take up the leftover 0-25 points works for most people.

**Comment by jlmelladovalle** [comment]
This is a long discussion with spanish community. At moment I tried this app, I asked them for this and people thought like me, as Warhammer, by points limit, not spent. In previous versions of Revolution Compedium was not clear, but I read 1.24 as you quoted, and cleared it now. A reason to think so, was that from 0 to 999 will not covered; and only if you spent exactly 2000 or 3000 was covered by those minimum and maximum, what appears to be an error… But if now it’s clearly defined in rules… we have to follow it.
I’m going to close this, and the merge request. If you need to recover it if in a future rules change as we thought, will be interesting to maintain that code.
Thank you.
