### ISSUE TITLE
Please add clickable link in Print view

### ISSUE THREAD

**Issue by LeadAddict** [dsusco/wm-selector#9]
The print view offers a QR code referencing the list but does not include a clickable link.

A clickable link would be useful to allow users to change a list after it has been saved as PDF. 

Right now your only option is to save the manual save link to restore a list.

**Comment by dsusco** [comment]
Most browsers put the URL of what you're printing in the footer, unfortunately it's always the print tab. Let me see if there's a way to change that to the URL under the saved tab before I add something programmatically.

**Comment by LeadAddict** [comment]
IIRC some browsers do truncate that URL. It's also not clickable if I am not mistaken.

**Comment by dsusco** [comment]
Added another print item for it.
